# Generated by Django 6.0.3 on 2026-03-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("message", models.CharField(blank=True, default="", max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Security", "Security"),
                            ("System", "System"),
                            ("Compliance", "Compliance"),
                            ("Analytics", "Analytics"),
                        ],
                        default="System",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unread_alerts", models.IntegerField(default=0)),
                ("total_today", models.IntegerField(default=0)),
                ("dismissed", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Alert stats",
            },
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("key", models.CharField(max_length=120)),
                ("created", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("user", models.CharField(max_length=120)),
                ("action", models.CharField(max_length=300)),
                ("module", models.CharField(max_length=60)),
                ("ip", models.GenericIPAddressField()),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("source_type", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=30)),
                ("records", models.CharField(blank=True, default="—", max_length=30)),
                ("last_sync", models.CharField(blank=True, default="—", max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DetectedPII",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=120)),
                ("field", models.CharField(max_length=120)),
                ("records", models.IntegerField(default=0)),
                ("masked", models.BooleanField(default=False)),
                ("confidence", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Detected PII",
                "verbose_name_plural": "Detected PII",
                "ordering": ["source"],
            },
        ),
        migrations.CreateModel(
            name="EntityDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(max_length=60)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-count"],
            },
        ),
        migrations.CreateModel(
            name="GeneralSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("value", models.CharField(blank=True, default="", max_length=200)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=20, unique=True)),
                ("source", models.CharField(max_length=120)),
                ("records", models.IntegerField(default=0)),
                ("status", models.CharField(max_length=30)),
                ("duration", models.CharField(blank=True, default="—", max_length=30)),
            ],
            options={
                "ordering": ["-job_id"],
            },
        ),
        migrations.CreateModel(
            name="IngestionStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_sources", models.IntegerField(default=0)),
                ("records_today", models.CharField(default="0", max_length=30)),
                ("failed_jobs", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Ingestion stats",
            },
        ),
        migrations.CreateModel(
            name="KpiSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_records_processed", models.BigIntegerField(default=0)),
                (
                    "records_change_text",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "records_change_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        max_length=10,
                    ),
                ),
                ("active_alerts", models.IntegerField(default=0)),
                (
                    "alerts_change_text",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "alerts_change_type",
                    models.CharField(default="neutral", max_length=10),
                ),
                ("identified_vulnerabilities", models.IntegerField(default=0)),
                (
                    "vulnerabilities_change_text",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "vulnerabilities_change_type",
                    models.CharField(default="neutral", max_length=10),
                ),
                ("pending_actions", models.IntegerField(default=0)),
                (
                    "actions_change_text",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "actions_change_type",
                    models.CharField(default="neutral", max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="MaskingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=120)),
                ("pattern", models.CharField(max_length=120)),
                ("mask_type", models.CharField(max_length=30)),
                ("applied", models.IntegerField(default=0)),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["field"],
            },
        ),
        migrations.CreateModel(
            name="MaskingStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pii_fields_detected", models.IntegerField(default=0)),
                ("fields_masked", models.IntegerField(default=0)),
                ("coverage_rate", models.CharField(default="0%", max_length=20)),
                ("active_rules", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Masking stats",
            },
        ),
        migrations.CreateModel(
            name="NlpAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_id", models.CharField(max_length=20, unique=True)),
                ("document", models.CharField(max_length=200)),
                ("entities", models.IntegerField(default=0)),
                ("sentiment", models.CharField(max_length=20)),
                ("topics", models.IntegerField(default=0)),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "NLP analyses",
                "ordering": ["-analysis_id"],
            },
        ),
        migrations.CreateModel(
            name="NlpStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documents_processed", models.CharField(default="0", max_length=30)),
                ("entities_extracted", models.CharField(default="0", max_length=30)),
                ("avg_confidence", models.CharField(default="0%", max_length=20)),
                ("active_models", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "NLP stats",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("enabled", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PlatformUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=30)),
                ("status", models.CharField(max_length=20)),
                (
                    "last_login",
                    models.CharField(blank=True, default="—", max_length=50),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("report_type", models.CharField(max_length=30)),
                ("generated", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=20)),
                ("status", models.CharField(default="Ready", max_length=20)),
            ],
            options={
                "ordering": ["-report_id"],
            },
        ),
        migrations.CreateModel(
            name="RiskByCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=60)),
                ("score", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Risk by category",
                "ordering": ["category"],
            },
        ),
        migrations.CreateModel(
            name="RiskScanStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_vulnerabilities", models.IntegerField(default=0)),
                ("critical", models.IntegerField(default=0)),
                ("in_progress", models.IntegerField(default=0)),
                ("resolved_30d", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Risk scan stats",
            },
        ),
        migrations.CreateModel(
            name="RiskTrendPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("risk", models.IntegerField()),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SecurityPosture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=60)),
                ("score", models.IntegerField(default=0)),
                ("full_mark", models.IntegerField(default=100)),
            ],
            options={
                "ordering": ["subject"],
            },
        ),
        migrations.CreateModel(
            name="SecuritySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("enabled", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SentimentDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("value", models.IntegerField(default=0)),
                ("color", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suggestion_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=30)),
                ("impact", models.CharField(max_length=10)),
                ("effort", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ["-suggestion_id"],
            },
        ),
        migrations.CreateModel(
            name="SuggestionStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open_suggestions", models.IntegerField(default=0)),
                ("in_review", models.IntegerField(default=0)),
                ("implemented", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Suggestion stats",
            },
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vuln_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("severity", models.CharField(max_length=10)),
                ("asset", models.CharField(max_length=120)),
                ("status", models.CharField(max_length=20)),
                ("discovered", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Vulnerabilities",
                "ordering": ["-vuln_id"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=120)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Vulnerability categories",
                "ordering": ["category"],
            },
        ),
    ]
